name: Draw QMK Keymap Layout

on:
  push:
    branches: [ "master" ]
    paths:
      - 'keyboards/cantor/keymaps/repparw/**'
      - '.github/workflows/draw_qmk_layout.yaml'
  workflow_dispatch:

jobs:
  call_draw_workflow:
    uses: repparw/keymap-drawer/.github/workflows/draw-qmk.yml@add-qmk-c-workflow # Pointer to your fork/branch
    with:
      qmk_keymap_c_path: 'keyboards/cantor/keymaps/repparw/keymap.c'
      qmk_keyboard: 'cantor'
      qmk_keymap: 'repparw'
      output_folder: 'docs'
      # You can add other optional inputs here if needed:
      # commit_message: 'style: Update keymap diagram'
      # amend_commit: false
      # fail_on_error: true
