name: Draw QMK Keymap Layout

uses: repparw/keymap-drawer/.github/workflows/draw-qmk.yml@add-qmk-c-workflow
with:
  qmk_keymap_c_path: 'keyboards/cantor/keymaps/repparw/keymap.c'
  qmk_keyboard: 'cantor'
  qmk_keymap: 'repparw'
  output_folder: 'docs'
